[package]
name = "typestuff"
version = "0.1.0"
authors = ["DenSASoftware <social@densa.software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
